apiVersion: v1
kind: Service
metadata:
  name: svc-taschen
  namespace: apptaschen
  labels:
    app: taschenrechner
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: taschenrechner
